# Makefile.rules for dbf
# Version 0.8
# History:
# $Log: Makefile.rules,v $
# Revision 1.5  2003/11/19 06:59:57  steinm
# - CHANGELOG is now ChangeLog
#
# Revision 1.4  2003/11/13 11:16:26  rollin_hand
# changed  to 'gcc' instead of full path
#
#

# Compiler flags
CC = gcc
CFLAGS = -Wall

# Settings
LOG = make.log
DIRS = src
BIN = dbf
VERSION = 0.8
PREFIX = /usr/local

# Compiler settings - do not change
# erased dbfversion.o
OBJ = an_string.o codepages.o congraph.o csv.o dbf.o endian.o iodbf.o sql.o statistic.o 
HDR = $(OBJ:%.o=%.h) tables.h
SRC = $(OBJ:%.o=%.c)
DOC = BUGS ChangeLog README CREDITS MANIFEST INSTALL FAQ


# Layout
YELLOW = \033[1;33m
NORMAL = \033[m
GREEN = \033[1;32m
RED = \033[1;31m

.c.o:
	$(CC) $(CFLAGS) -c $<
