# Makefile.rules for dbf
# Version 0.6

# Compiler flags
CC = /usr/bin/gcc
CFLAGS = -Wall

# Settings
LOG = make.log
DIRS = src
BIN = dbf
VERSION = 0.6
PREFIX = /usr/local/bin

# Layout
YELLOW = \033[1;33m
NORMAL = \033[m
GREEN = \033[1;32m
RED = \033[1;31m

.c.o:
	$(CC) $(CFLAGS) -c $<
